# Generated by Django 4.0.6 on 2023-09-01 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filelist',
            name='file_path',
        ),
        migrations.AddField(
            model_name='filelist',
            name='파일',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
