# Generated by Django 4.0.6 on 2023-09-04 06:00

from django.db import migrations, models
import forecast.models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0002_remove_filelist_file_path_filelist_파일'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filelist',
            options={},
        ),
        migrations.AlterModelOptions(
            name='graphlist',
            options={},
        ),
        migrations.AlterModelOptions(
            name='modellist',
            options={},
        ),
        migrations.AlterModelOptions(
            name='predlist',
            options={},
        ),
        migrations.AlterField(
            model_name='filelist',
            name='created_dt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='filelist',
            name='파일',
            field=models.FileField(null=True, upload_to=forecast.models.upload_to_today),
        ),
    ]
