# Generated by Django 4.0.6 on 2023-09-12 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0004_filelist_진행현황'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modellist',
            name='created_dt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='predlist',
            name='created_dt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
