# Generated by Django 4.0.6 on 2023-09-12 06:28

from django.db import migrations, models
import django.db.models.deletion
import forecast.models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0006_predlist_file_alter_predlist_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphlist',
            name='path1',
        ),
        migrations.RemoveField(
            model_name='graphlist',
            name='path2',
        ),
        migrations.RemoveField(
            model_name='graphlist',
            name='path3',
        ),
        migrations.RemoveField(
            model_name='graphlist',
            name='path4',
        ),
        migrations.AddField(
            model_name='graphlist',
            name='file',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='forecast.filelist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graphlist',
            name='file1',
            field=models.FileField(null=True, upload_to=forecast.models.upload_to_today),
        ),
        migrations.AddField(
            model_name='graphlist',
            name='file2',
            field=models.FileField(null=True, upload_to=forecast.models.upload_to_today),
        ),
        migrations.AddField(
            model_name='graphlist',
            name='file3',
            field=models.FileField(null=True, upload_to=forecast.models.upload_to_today),
        ),
        migrations.AddField(
            model_name='graphlist',
            name='file4',
            field=models.FileField(null=True, upload_to=forecast.models.upload_to_today),
        ),
    ]
