# Generated by Django 4.0.6 on 2023-09-12 07:27

from django.db import migrations, models
import forecast.models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0007_remove_graphlist_path1_remove_graphlist_path2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphlist',
            name='file1',
        ),
        migrations.RemoveField(
            model_name='graphlist',
            name='file2',
        ),
        migrations.RemoveField(
            model_name='graphlist',
            name='file3',
        ),
        migrations.RemoveField(
            model_name='graphlist',
            name='file4',
        ),
        migrations.AddField(
            model_name='graphlist',
            name='image1',
            field=models.ImageField(default='default.png', upload_to=forecast.models.upload_to_today),
        ),
        migrations.AddField(
            model_name='graphlist',
            name='image2',
            field=models.ImageField(default='default.png', upload_to=forecast.models.upload_to_today),
        ),
        migrations.AddField(
            model_name='graphlist',
            name='image3',
            field=models.ImageField(default='default.png', upload_to=forecast.models.upload_to_today),
        ),
        migrations.AddField(
            model_name='graphlist',
            name='image4',
            field=models.ImageField(default='default.png', upload_to=forecast.models.upload_to_today),
        ),
    ]
