# Generated by Django 4.0.6 on 2023-09-19 01:20

from django.db import migrations, models
import forecast.models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0008_remove_graphlist_file1_remove_graphlist_file2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphlist',
            name='chart_image',
            field=models.ImageField(default='default.png', upload_to=forecast.models.upload_to_today),
        ),
    ]
