# Generated by Django 4.0.6 on 2023-09-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0009_graphlist_chart_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predlist',
            name='pred_value',
            field=models.FloatField(null=True, verbose_name='예측값'),
        ),
        migrations.AlterField(
            model_name='predlist',
            name='real_value',
            field=models.FloatField(null=True, verbose_name='실측값'),
        ),
    ]
