# Generated by Django 4.0.6 on 2023-09-27 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0010_alter_predlist_pred_value_alter_predlist_real_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graphlist',
            old_name='chart_image',
            new_name='image0',
        ),
    ]
